### PR TITLE
Cleaned Up Godot Assets Structure

### PR DESCRIPTION
**Pull request by BrickPi**
- Added Application Icons for Windows, Mac, and Linux
- Localised "Asset Path Not Found" message box and reworded message to be less technical.
- Moved `localisation` to `assets/localisation`
- Moved `audio` to `assets/audio`
- Removed legacy assets from repo pending custom mode, still retained in Google Drive.
- Moved `quotes.txt` and `credits.csv` to `assets/localisation`
- Removed unused assets in `common`
- Moved `theme` to `assets/graphics/theme`
- Moved used assets under `art` to `assets/graphics`

All suggestions are welcome.

Open to extending reorganisation to the `src` folder to reflect new needs after pivoting to compatibility.

Eventually will need to refactor credits to better reflect organisation of project and accretion of new contributors.

_All modified features tested and working._ :-)

### CODE REVIEW

**Review by Spartan322 — CHANGES_REQUESTED** [review]
Linux crashes with `WARNING: Icon too large, attempting to resize icon.`

**Comment by Spartan322** [comment]
Something is seriously wrong with running the files built on Ubuntu on Arch Linux.

**Review by Hop311 — COMMENTED** [review]
When I exported locally and tried running the exe, the whole screen would get a white tint, like when a program stops responding, and then just stopped, so something's broken (this was yesterday morning, I'll try again with the recent changes later today).

**Comment by BrickPi** [comment]
Everything should finally be fixed and working 😭

**Review by Spartan322 — APPROVED** [review]

**Pull request merged**
